/*
BSD 2-Clause License

Copyright (c) 2024, badcoiq
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#pragma once
#ifndef __SUBPIXEL_H_
#define __SUBPIXEL_H_

/*! Fixed point math inevitably introduces rounding error to the DDA. The error is
 *  fixed every now and then by a separate fix value. The defines below set these.
 */
#define SLOPE_FIX_SHIFT 8
#define SLOPE_FIX_STEP (1 << SLOPE_FIX_SHIFT)
#define SLOPE_FIX_MASK (SLOPE_FIX_STEP - 1)
#define SLOPE_FIX_SCANLINES (1 << (SLOPE_FIX_SHIFT - SUBPIXEL_SHIFT))
#define SLOPE_FIX_SCANLINE_MASK (SLOPE_FIX_SCANLINES - 1)
#define SUBPIXEL_SHIFT 3
 /*
 8x8 sparse supersampling mask:

 [][][][][]##[][] 5
 ##[][][][][][][] 0
 [][][]##[][][][] 3
 [][][][][][]##[] 6
 []##[][][][][][] 1
 [][][][]##[][][] 4
 [][][][][][][]## 7
 [][]##[][][][][] 2

 16x16 sparse supersampling mask:

 []##[][][][][][][][][][][][][][] 1
 [][][][][][][][]##[][][][][][][] 8
 [][][][]##[][][][][][][][][][][] 4
 [][][][][][][][][][][][][][][]## 15
 [][][][][][][][][][][]##[][][][] 11
 [][]##[][][][][][][][][][][][][] 2
 [][][][][][]##[][][][][][][][][] 6
 [][][][][][][][][][][][][][]##[] 14
 [][][][][][][][][][]##[][][][][] 10
 [][][]##[][][][][][][][][][][][] 3
 [][][][][][][]##[][][][][][][][] 7
 [][][][][][][][][][][][]##[][][] 12
 ##[][][][][][][][][][][][][][][] 0
 [][][][][][][][][]##[][][][][][] 9
 [][][][][]##[][][][][][][][][][] 5
 [][][][][][][][][][][][][]##[][] 13

 32x32 sparse supersampling mask

 [][][][][][][][][][][][][][][][][][][][][][][][][][][][]##[][][] 28
 [][][][][][][][][][][][][]##[][][][][][][][][][][][][][][][][][] 13
 [][][][][][]##[][][][][][][][][][][][][][][][][][][][][][][][][] 6
 [][][][][][][][][][][][][][][][][][][][][][][]##[][][][][][][][] 23
 ##[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][] 0
 [][][][][][][][][][][][][][][][][]##[][][][][][][][][][][][][][] 17
 [][][][][][][][][][]##[][][][][][][][][][][][][][][][][][][][][] 10
 [][][][][][][][][][][][][][][][][][][][][][][][][][][]##[][][][] 27
 [][][][]##[][][][][][][][][][][][][][][][][][][][][][][][][][][] 4
 [][][][][][][][][][][][][][][][][][][][][]##[][][][][][][][][][] 21
 [][][][][][][][][][][][][][]##[][][][][][][][][][][][][][][][][] 14
 [][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]## 31
 [][][][][][][][]##[][][][][][][][][][][][][][][][][][][][][][][] 8
 [][][][][][][][][][][][][][][][][][][][][][][][][]##[][][][][][] 25
 [][][][][][][][][][][][][][][][][][]##[][][][][][][][][][][][][] 18
 [][][]##[][][][][][][][][][][][][][][][][][][][][][][][][][][][] 3
 [][][][][][][][][][][][]##[][][][][][][][][][][][][][][][][][][] 12
 [][][][][][][][][][][][][][][][][][][][][][][][][][][][][]##[][] 29
 [][][][][][][][][][][][][][][][][][][][][][]##[][][][][][][][][] 22
 [][][][][][][]##[][][][][][][][][][][][][][][][][][][][][][][][] 7
 [][][][][][][][][][][][][][][][]##[][][][][][][][][][][][][][][] 16
 []##[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][] 1
 [][][][][][][][][][][][][][][][][][][][][][][][][][]##[][][][][] 26
 [][][][][][][][][][][]##[][][][][][][][][][][][][][][][][][][][] 11
 [][][][][][][][][][][][][][][][][][][][]##[][][][][][][][][][][] 20
 [][][][][]##[][][][][][][][][][][][][][][][][][][][][][][][][][] 5
 [][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]##[] 30
 [][][][][][][][][][][][][][][]##[][][][][][][][][][][][][][][][] 15
 [][][][][][][][][][][][][][][][][][][][][][][][]##[][][][][][][] 24
 [][][][][][][][][]##[][][][][][][][][][][][][][][][][][][][][][] 9
 [][]##[][][][][][][][][][][][][][][][][][][][][][][][][][][][][] 2
 [][][][][][][][][][][][][][][][][][][]##[][][][][][][][][][][][] 19
*/

#define SUBPIXEL_COUNT (1 << SUBPIXEL_SHIFT)

#if SUBPIXEL_SHIFT == 3
//#define SUBPIXEL_DATA unsigned char
#define WINDING_DATA unsigned __int64
#define SUBPIXEL_COVERAGE(a) (coverageTable[(a)])

#define SUBPIXEL_OFFSET_0 (5.0f/8.0f)
#define SUBPIXEL_OFFSET_1 (0.0f/8.0f)
#define SUBPIXEL_OFFSET_2 (3.0f/8.0f)
#define SUBPIXEL_OFFSET_3 (6.0f/8.0f)
#define SUBPIXEL_OFFSET_4 (1.0f/8.0f)
#define SUBPIXEL_OFFSET_5 (4.0f/8.0f)
#define SUBPIXEL_OFFSET_6 (7.0f/8.0f)
#define SUBPIXEL_OFFSET_7 (2.0f/8.0f)

#define SUBPIXEL_OFFSET_RATIONAL_0 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_0)
#define SUBPIXEL_OFFSET_RATIONAL_1 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_1)
#define SUBPIXEL_OFFSET_RATIONAL_2 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_2)
#define SUBPIXEL_OFFSET_RATIONAL_3 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_3)
#define SUBPIXEL_OFFSET_RATIONAL_4 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_4)
#define SUBPIXEL_OFFSET_RATIONAL_5 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_5)
#define SUBPIXEL_OFFSET_RATIONAL_6 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_6)
#define SUBPIXEL_OFFSET_RATIONAL_7 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_7)

#define SUBPIXEL_OFFSET_FIXED_0 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_0)
#define SUBPIXEL_OFFSET_FIXED_1 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_1)
#define SUBPIXEL_OFFSET_FIXED_2 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_2)
#define SUBPIXEL_OFFSET_FIXED_3 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_3)
#define SUBPIXEL_OFFSET_FIXED_4 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_4)
#define SUBPIXEL_OFFSET_FIXED_5 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_5)
#define SUBPIXEL_OFFSET_FIXED_6 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_6)
#define SUBPIXEL_OFFSET_FIXED_7 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_7)

#define SUBPIXEL_OFFSETS { SUBPIXEL_OFFSET_RATIONAL_0,\
                           SUBPIXEL_OFFSET_RATIONAL_1,\
                           SUBPIXEL_OFFSET_RATIONAL_2,\
                           SUBPIXEL_OFFSET_RATIONAL_3,\
                           SUBPIXEL_OFFSET_RATIONAL_4,\
                           SUBPIXEL_OFFSET_RATIONAL_5,\
                           SUBPIXEL_OFFSET_RATIONAL_6,\
                           SUBPIXEL_OFFSET_RATIONAL_7 }

#define SUBPIXEL_OFFSETS_FIXED { SUBPIXEL_OFFSET_FIXED_0,\
                                 SUBPIXEL_OFFSET_FIXED_1,\
                                 SUBPIXEL_OFFSET_FIXED_2,\
                                 SUBPIXEL_OFFSET_FIXED_3,\
                                 SUBPIXEL_OFFSET_FIXED_4,\
                                 SUBPIXEL_OFFSET_FIXED_5,\
                                 SUBPIXEL_OFFSET_FIXED_6,\
                                 SUBPIXEL_OFFSET_FIXED_7 }

#define SUBPIXEL_FULL_COVERAGE 0xff
#elif SUBPIXEL_SHIFT == 4
#define SUBPIXEL_DATA unsigned short
#define SUBPIXEL_COVERAGE(a) (coverageTable[(a) & 0xff] + coverageTable[((a) >> 8) & 0xff])

#define SUBPIXEL_OFFSET_0  (1.0f/16.0f)
#define SUBPIXEL_OFFSET_1  (8.0f/16.0f)
#define SUBPIXEL_OFFSET_2  (4.0f/16.0f)
#define SUBPIXEL_OFFSET_3  (15.0f/16.0f)
#define SUBPIXEL_OFFSET_4  (11.0f/16.0f)
#define SUBPIXEL_OFFSET_5  (2.0f/16.0f)
#define SUBPIXEL_OFFSET_6  (6.0f/16.0f)
#define SUBPIXEL_OFFSET_7  (14.0f/16.0f)
#define SUBPIXEL_OFFSET_8  (10.0f/16.0f)
#define SUBPIXEL_OFFSET_9  (3.0f/16.0f)
#define SUBPIXEL_OFFSET_10 (7.0f/16.0f)
#define SUBPIXEL_OFFSET_11 (12.0f/16.0f)
#define SUBPIXEL_OFFSET_12 (0.0f/16.0f)
#define SUBPIXEL_OFFSET_13 (9.0f/16.0f)
#define SUBPIXEL_OFFSET_14 (5.0f/16.0f)
#define SUBPIXEL_OFFSET_15 (13.0f/16.0f)

#define SUBPIXEL_OFFSET_RATIONAL_0 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_0)
#define SUBPIXEL_OFFSET_RATIONAL_1 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_1)
#define SUBPIXEL_OFFSET_RATIONAL_2 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_2)
#define SUBPIXEL_OFFSET_RATIONAL_3 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_3)
#define SUBPIXEL_OFFSET_RATIONAL_4 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_4)
#define SUBPIXEL_OFFSET_RATIONAL_5 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_5)
#define SUBPIXEL_OFFSET_RATIONAL_6 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_6)
#define SUBPIXEL_OFFSET_RATIONAL_7 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_7)
#define SUBPIXEL_OFFSET_RATIONAL_8 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_8)
#define SUBPIXEL_OFFSET_RATIONAL_9 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_9)
#define SUBPIXEL_OFFSET_RATIONAL_10 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_10)
#define SUBPIXEL_OFFSET_RATIONAL_11 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_11)
#define SUBPIXEL_OFFSET_RATIONAL_12 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_12)
#define SUBPIXEL_OFFSET_RATIONAL_13 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_13)
#define SUBPIXEL_OFFSET_RATIONAL_14 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_14)
#define SUBPIXEL_OFFSET_RATIONAL_15 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_15)

#define SUBPIXEL_OFFSET_FIXED_0 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_0)
#define SUBPIXEL_OFFSET_FIXED_1 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_1)
#define SUBPIXEL_OFFSET_FIXED_2 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_2)
#define SUBPIXEL_OFFSET_FIXED_3 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_3)
#define SUBPIXEL_OFFSET_FIXED_4 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_4)
#define SUBPIXEL_OFFSET_FIXED_5 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_5)
#define SUBPIXEL_OFFSET_FIXED_6 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_6)
#define SUBPIXEL_OFFSET_FIXED_7 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_7)
#define SUBPIXEL_OFFSET_FIXED_8 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_8)
#define SUBPIXEL_OFFSET_FIXED_9 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_9)
#define SUBPIXEL_OFFSET_FIXED_10 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_10)
#define SUBPIXEL_OFFSET_FIXED_11 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_11)
#define SUBPIXEL_OFFSET_FIXED_12 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_12)
#define SUBPIXEL_OFFSET_FIXED_13 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_13)
#define SUBPIXEL_OFFSET_FIXED_14 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_14)
#define SUBPIXEL_OFFSET_FIXED_15 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_15)

#define SUBPIXEL_OFFSETS { SUBPIXEL_OFFSET_RATIONAL_0,\
                           SUBPIXEL_OFFSET_RATIONAL_1,\
                           SUBPIXEL_OFFSET_RATIONAL_2,\
                           SUBPIXEL_OFFSET_RATIONAL_3,\
                           SUBPIXEL_OFFSET_RATIONAL_4,\
                           SUBPIXEL_OFFSET_RATIONAL_5,\
                           SUBPIXEL_OFFSET_RATIONAL_6,\
                           SUBPIXEL_OFFSET_RATIONAL_7,\
                           SUBPIXEL_OFFSET_RATIONAL_8,\
                           SUBPIXEL_OFFSET_RATIONAL_9,\
                           SUBPIXEL_OFFSET_RATIONAL_10,\
                           SUBPIXEL_OFFSET_RATIONAL_11,\
                           SUBPIXEL_OFFSET_RATIONAL_12,\
                           SUBPIXEL_OFFSET_RATIONAL_13,\
                           SUBPIXEL_OFFSET_RATIONAL_14,\
                           SUBPIXEL_OFFSET_RATIONAL_15 }

#define SUBPIXEL_OFFSETS_FIXED { SUBPIXEL_OFFSET_FIXED_0,\
                                 SUBPIXEL_OFFSET_FIXED_1,\
                                 SUBPIXEL_OFFSET_FIXED_2,\
                                 SUBPIXEL_OFFSET_FIXED_3,\
                                 SUBPIXEL_OFFSET_FIXED_4,\
                                 SUBPIXEL_OFFSET_FIXED_5,\
                                 SUBPIXEL_OFFSET_FIXED_6,\
                                 SUBPIXEL_OFFSET_FIXED_7,\
                                 SUBPIXEL_OFFSET_FIXED_8,\
                                 SUBPIXEL_OFFSET_FIXED_9,\
                                 SUBPIXEL_OFFSET_FIXED_10,\
                                 SUBPIXEL_OFFSET_FIXED_11,\
                                 SUBPIXEL_OFFSET_FIXED_12,\
                                 SUBPIXEL_OFFSET_FIXED_13,\
                                 SUBPIXEL_OFFSET_FIXED_14,\
                                 SUBPIXEL_OFFSET_FIXED_15 }

#define SUBPIXEL_FULL_COVERAGE 0xffff
#elif SUBPIXEL_SHIFT == 5
#define SUBPIXEL_DATA unsigned long
#define SUBPIXEL_COVERAGE(a) (coverageTable[(a) & 0xff] + coverageTable[((a) >> 8) & 0xff] + coverageTable[((a) >> 16) & 0xff] + coverageTable[((a) >> 24) & 0xff])

#define SUBPIXEL_OFFSET_0  (28.0f/32.0f)
#define SUBPIXEL_OFFSET_1  (13.0f/32.0f)
#define SUBPIXEL_OFFSET_2  (6.0f/32.0f)
#define SUBPIXEL_OFFSET_3  (23.0f/32.0f)
#define SUBPIXEL_OFFSET_4  (0.0f/32.0f)
#define SUBPIXEL_OFFSET_5  (17.0f/32.0f)
#define SUBPIXEL_OFFSET_6  (10.0f/32.0f)
#define SUBPIXEL_OFFSET_7  (27.0f/32.0f)
#define SUBPIXEL_OFFSET_8  (4.0f/32.0f)
#define SUBPIXEL_OFFSET_9  (21.0f/32.0f)
#define SUBPIXEL_OFFSET_10 (14.0f/32.0f)
#define SUBPIXEL_OFFSET_11 (31.0f/32.0f)
#define SUBPIXEL_OFFSET_12 (8.0f/32.0f)
#define SUBPIXEL_OFFSET_13 (25.0f/32.0f)
#define SUBPIXEL_OFFSET_14 (18.0f/32.0f)
#define SUBPIXEL_OFFSET_15 (3.0f/32.0f)
#define SUBPIXEL_OFFSET_16 (12.0f/32.0f)
#define SUBPIXEL_OFFSET_17 (29.0f/32.0f)
#define SUBPIXEL_OFFSET_18 (22.0f/32.0f)
#define SUBPIXEL_OFFSET_19 (7.0f/32.0f)
#define SUBPIXEL_OFFSET_20 (16.0f/32.0f)
#define SUBPIXEL_OFFSET_21 (1.0f/32.0f)
#define SUBPIXEL_OFFSET_22 (26.0f/32.0f)
#define SUBPIXEL_OFFSET_23 (11.0f/32.0f)
#define SUBPIXEL_OFFSET_24 (20.0f/32.0f)
#define SUBPIXEL_OFFSET_25 (5.0f/32.0f)
#define SUBPIXEL_OFFSET_26 (30.0f/32.0f)
#define SUBPIXEL_OFFSET_27 (15.0f/32.0f)
#define SUBPIXEL_OFFSET_28 (24.0f/32.0f)
#define SUBPIXEL_OFFSET_29 (9.0f/32.0f)
#define SUBPIXEL_OFFSET_30 (2.0f/32.0f)
#define SUBPIXEL_OFFSET_31 (19.0f/32.0f)

#define SUBPIXEL_OFFSET_RATIONAL_0 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_0)
#define SUBPIXEL_OFFSET_RATIONAL_1 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_1)
#define SUBPIXEL_OFFSET_RATIONAL_2 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_2)
#define SUBPIXEL_OFFSET_RATIONAL_3 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_3)
#define SUBPIXEL_OFFSET_RATIONAL_4 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_4)
#define SUBPIXEL_OFFSET_RATIONAL_5 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_5)
#define SUBPIXEL_OFFSET_RATIONAL_6 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_6)
#define SUBPIXEL_OFFSET_RATIONAL_7 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_7)
#define SUBPIXEL_OFFSET_RATIONAL_8 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_8)
#define SUBPIXEL_OFFSET_RATIONAL_9 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_9)
#define SUBPIXEL_OFFSET_RATIONAL_10 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_10)
#define SUBPIXEL_OFFSET_RATIONAL_11 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_11)
#define SUBPIXEL_OFFSET_RATIONAL_12 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_12)
#define SUBPIXEL_OFFSET_RATIONAL_13 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_13)
#define SUBPIXEL_OFFSET_RATIONAL_14 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_14)
#define SUBPIXEL_OFFSET_RATIONAL_15 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_15)
#define SUBPIXEL_OFFSET_RATIONAL_16 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_16)
#define SUBPIXEL_OFFSET_RATIONAL_17 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_17)
#define SUBPIXEL_OFFSET_RATIONAL_18 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_18)
#define SUBPIXEL_OFFSET_RATIONAL_19 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_19)
#define SUBPIXEL_OFFSET_RATIONAL_20 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_20)
#define SUBPIXEL_OFFSET_RATIONAL_21 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_21)
#define SUBPIXEL_OFFSET_RATIONAL_22 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_22)
#define SUBPIXEL_OFFSET_RATIONAL_23 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_23)
#define SUBPIXEL_OFFSET_RATIONAL_24 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_24)
#define SUBPIXEL_OFFSET_RATIONAL_25 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_25)
#define SUBPIXEL_OFFSET_RATIONAL_26 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_26)
#define SUBPIXEL_OFFSET_RATIONAL_27 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_27)
#define SUBPIXEL_OFFSET_RATIONAL_28 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_28)
#define SUBPIXEL_OFFSET_RATIONAL_29 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_29)
#define SUBPIXEL_OFFSET_RATIONAL_30 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_30)
#define SUBPIXEL_OFFSET_RATIONAL_31 FLOAT_TO_RATIONAL(SUBPIXEL_OFFSET_31)

#define SUBPIXEL_OFFSET_FIXED_0 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_0)
#define SUBPIXEL_OFFSET_FIXED_1 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_1)
#define SUBPIXEL_OFFSET_FIXED_2 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_2)
#define SUBPIXEL_OFFSET_FIXED_3 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_3)
#define SUBPIXEL_OFFSET_FIXED_4 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_4)
#define SUBPIXEL_OFFSET_FIXED_5 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_5)
#define SUBPIXEL_OFFSET_FIXED_6 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_6)
#define SUBPIXEL_OFFSET_FIXED_7 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_7)
#define SUBPIXEL_OFFSET_FIXED_8 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_8)
#define SUBPIXEL_OFFSET_FIXED_9 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_9)
#define SUBPIXEL_OFFSET_FIXED_10 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_10)
#define SUBPIXEL_OFFSET_FIXED_11 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_11)
#define SUBPIXEL_OFFSET_FIXED_12 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_12)
#define SUBPIXEL_OFFSET_FIXED_13 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_13)
#define SUBPIXEL_OFFSET_FIXED_14 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_14)
#define SUBPIXEL_OFFSET_FIXED_15 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_15)
#define SUBPIXEL_OFFSET_FIXED_16 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_16)
#define SUBPIXEL_OFFSET_FIXED_17 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_17)
#define SUBPIXEL_OFFSET_FIXED_18 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_18)
#define SUBPIXEL_OFFSET_FIXED_19 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_19)
#define SUBPIXEL_OFFSET_FIXED_20 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_20)
#define SUBPIXEL_OFFSET_FIXED_21 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_21)
#define SUBPIXEL_OFFSET_FIXED_22 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_22)
#define SUBPIXEL_OFFSET_FIXED_23 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_23)
#define SUBPIXEL_OFFSET_FIXED_24 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_24)
#define SUBPIXEL_OFFSET_FIXED_25 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_25)
#define SUBPIXEL_OFFSET_FIXED_26 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_26)
#define SUBPIXEL_OFFSET_FIXED_27 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_27)
#define SUBPIXEL_OFFSET_FIXED_28 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_28)
#define SUBPIXEL_OFFSET_FIXED_29 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_29)
#define SUBPIXEL_OFFSET_FIXED_30 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_30)
#define SUBPIXEL_OFFSET_FIXED_31 FLOAT_TO_FIXED(SUBPIXEL_OFFSET_31)

#define SUBPIXEL_OFFSETS { SUBPIXEL_OFFSET_RATIONAL_0,\
                           SUBPIXEL_OFFSET_RATIONAL_1,\
                           SUBPIXEL_OFFSET_RATIONAL_2,\
                           SUBPIXEL_OFFSET_RATIONAL_3,\
                           SUBPIXEL_OFFSET_RATIONAL_4,\
                           SUBPIXEL_OFFSET_RATIONAL_5,\
                           SUBPIXEL_OFFSET_RATIONAL_6,\
                           SUBPIXEL_OFFSET_RATIONAL_7,\
                           SUBPIXEL_OFFSET_RATIONAL_8,\
                           SUBPIXEL_OFFSET_RATIONAL_9,\
                           SUBPIXEL_OFFSET_RATIONAL_10,\
                           SUBPIXEL_OFFSET_RATIONAL_11,\
                           SUBPIXEL_OFFSET_RATIONAL_12,\
                           SUBPIXEL_OFFSET_RATIONAL_13,\
                           SUBPIXEL_OFFSET_RATIONAL_14,\
                           SUBPIXEL_OFFSET_RATIONAL_15,\
                           SUBPIXEL_OFFSET_RATIONAL_16,\
                           SUBPIXEL_OFFSET_RATIONAL_17,\
                           SUBPIXEL_OFFSET_RATIONAL_18,\
                           SUBPIXEL_OFFSET_RATIONAL_19,\
                           SUBPIXEL_OFFSET_RATIONAL_20,\
                           SUBPIXEL_OFFSET_RATIONAL_21,\
                           SUBPIXEL_OFFSET_RATIONAL_22,\
                           SUBPIXEL_OFFSET_RATIONAL_23,\
                           SUBPIXEL_OFFSET_RATIONAL_24,\
                           SUBPIXEL_OFFSET_RATIONAL_25,\
                           SUBPIXEL_OFFSET_RATIONAL_26,\
                           SUBPIXEL_OFFSET_RATIONAL_27,\
                           SUBPIXEL_OFFSET_RATIONAL_28,\
                           SUBPIXEL_OFFSET_RATIONAL_29,\
                           SUBPIXEL_OFFSET_RATIONAL_30,\
                           SUBPIXEL_OFFSET_RATIONAL_31 }

#define SUBPIXEL_OFFSETS_FIXED { SUBPIXEL_OFFSET_FIXED_0,\
                                 SUBPIXEL_OFFSET_FIXED_1,\
                                 SUBPIXEL_OFFSET_FIXED_2,\
                                 SUBPIXEL_OFFSET_FIXED_3,\
                                 SUBPIXEL_OFFSET_FIXED_4,\
                                 SUBPIXEL_OFFSET_FIXED_5,\
                                 SUBPIXEL_OFFSET_FIXED_6,\
                                 SUBPIXEL_OFFSET_FIXED_7,\
                                 SUBPIXEL_OFFSET_FIXED_8,\
                                 SUBPIXEL_OFFSET_FIXED_9,\
                                 SUBPIXEL_OFFSET_FIXED_10,\
                                 SUBPIXEL_OFFSET_FIXED_11,\
                                 SUBPIXEL_OFFSET_FIXED_12,\
                                 SUBPIXEL_OFFSET_FIXED_13,\
                                 SUBPIXEL_OFFSET_FIXED_14,\
                                 SUBPIXEL_OFFSET_FIXED_15,\
                                 SUBPIXEL_OFFSET_FIXED_16,\
                                 SUBPIXEL_OFFSET_FIXED_17,\
                                 SUBPIXEL_OFFSET_FIXED_18,\
                                 SUBPIXEL_OFFSET_FIXED_19,\
                                 SUBPIXEL_OFFSET_FIXED_20,\
                                 SUBPIXEL_OFFSET_FIXED_21,\
                                 SUBPIXEL_OFFSET_FIXED_22,\
                                 SUBPIXEL_OFFSET_FIXED_23,\
                                 SUBPIXEL_OFFSET_FIXED_24,\
                                 SUBPIXEL_OFFSET_FIXED_25,\
                                 SUBPIXEL_OFFSET_FIXED_26,\
                                 SUBPIXEL_OFFSET_FIXED_27,\
                                 SUBPIXEL_OFFSET_FIXED_28,\
                                 SUBPIXEL_OFFSET_FIXED_29,\
                                 SUBPIXEL_OFFSET_FIXED_30,\
                                 SUBPIXEL_OFFSET_FIXED_31 }

#define SUBPIXEL_FULL_COVERAGE 0xffffffff
#endif

#define PIXEL_COVERAGE(a) (((a) & 1) + (((a) >> 1) & 1) + (((a) >> 2) & 1) + (((a) >> 3) & 1) +\
                           (((a) >> 4) & 1) + (((a) >> 5) & 1) + (((a) >> 6) & 1) + (((a) >> 7) & 1))

static const unsigned char coverageTable[256] = {
    PIXEL_COVERAGE(0x00),PIXEL_COVERAGE(0x01),PIXEL_COVERAGE(0x02),PIXEL_COVERAGE(0x03),
    PIXEL_COVERAGE(0x04),PIXEL_COVERAGE(0x05),PIXEL_COVERAGE(0x06),PIXEL_COVERAGE(0x07),
    PIXEL_COVERAGE(0x08),PIXEL_COVERAGE(0x09),PIXEL_COVERAGE(0x0a),PIXEL_COVERAGE(0x0b),
    PIXEL_COVERAGE(0x0c),PIXEL_COVERAGE(0x0d),PIXEL_COVERAGE(0x0e),PIXEL_COVERAGE(0x0f),
    PIXEL_COVERAGE(0x10),PIXEL_COVERAGE(0x11),PIXEL_COVERAGE(0x12),PIXEL_COVERAGE(0x13),
    PIXEL_COVERAGE(0x14),PIXEL_COVERAGE(0x15),PIXEL_COVERAGE(0x16),PIXEL_COVERAGE(0x17),
    PIXEL_COVERAGE(0x18),PIXEL_COVERAGE(0x19),PIXEL_COVERAGE(0x1a),PIXEL_COVERAGE(0x1b),
    PIXEL_COVERAGE(0x1c),PIXEL_COVERAGE(0x1d),PIXEL_COVERAGE(0x1e),PIXEL_COVERAGE(0x1f),
    PIXEL_COVERAGE(0x20),PIXEL_COVERAGE(0x21),PIXEL_COVERAGE(0x22),PIXEL_COVERAGE(0x23),
    PIXEL_COVERAGE(0x24),PIXEL_COVERAGE(0x25),PIXEL_COVERAGE(0x26),PIXEL_COVERAGE(0x27),
    PIXEL_COVERAGE(0x28),PIXEL_COVERAGE(0x29),PIXEL_COVERAGE(0x2a),PIXEL_COVERAGE(0x2b),
    PIXEL_COVERAGE(0x2c),PIXEL_COVERAGE(0x2d),PIXEL_COVERAGE(0x2e),PIXEL_COVERAGE(0x2f),
    PIXEL_COVERAGE(0x30),PIXEL_COVERAGE(0x31),PIXEL_COVERAGE(0x32),PIXEL_COVERAGE(0x33),
    PIXEL_COVERAGE(0x34),PIXEL_COVERAGE(0x35),PIXEL_COVERAGE(0x36),PIXEL_COVERAGE(0x37),
    PIXEL_COVERAGE(0x38),PIXEL_COVERAGE(0x39),PIXEL_COVERAGE(0x3a),PIXEL_COVERAGE(0x3b),
    PIXEL_COVERAGE(0x3c),PIXEL_COVERAGE(0x3d),PIXEL_COVERAGE(0x3e),PIXEL_COVERAGE(0x3f),
    PIXEL_COVERAGE(0x40),PIXEL_COVERAGE(0x41),PIXEL_COVERAGE(0x42),PIXEL_COVERAGE(0x43),
    PIXEL_COVERAGE(0x44),PIXEL_COVERAGE(0x45),PIXEL_COVERAGE(0x46),PIXEL_COVERAGE(0x47),
    PIXEL_COVERAGE(0x48),PIXEL_COVERAGE(0x49),PIXEL_COVERAGE(0x4a),PIXEL_COVERAGE(0x4b),
    PIXEL_COVERAGE(0x4c),PIXEL_COVERAGE(0x4d),PIXEL_COVERAGE(0x4e),PIXEL_COVERAGE(0x4f),
    PIXEL_COVERAGE(0x50),PIXEL_COVERAGE(0x51),PIXEL_COVERAGE(0x52),PIXEL_COVERAGE(0x53),
    PIXEL_COVERAGE(0x54),PIXEL_COVERAGE(0x55),PIXEL_COVERAGE(0x56),PIXEL_COVERAGE(0x57),
    PIXEL_COVERAGE(0x58),PIXEL_COVERAGE(0x59),PIXEL_COVERAGE(0x5a),PIXEL_COVERAGE(0x5b),
    PIXEL_COVERAGE(0x5c),PIXEL_COVERAGE(0x5d),PIXEL_COVERAGE(0x5e),PIXEL_COVERAGE(0x5f),
    PIXEL_COVERAGE(0x60),PIXEL_COVERAGE(0x61),PIXEL_COVERAGE(0x62),PIXEL_COVERAGE(0x63),
    PIXEL_COVERAGE(0x64),PIXEL_COVERAGE(0x65),PIXEL_COVERAGE(0x66),PIXEL_COVERAGE(0x67),
    PIXEL_COVERAGE(0x68),PIXEL_COVERAGE(0x69),PIXEL_COVERAGE(0x6a),PIXEL_COVERAGE(0x6b),
    PIXEL_COVERAGE(0x6c),PIXEL_COVERAGE(0x6d),PIXEL_COVERAGE(0x6e),PIXEL_COVERAGE(0x6f),
    PIXEL_COVERAGE(0x70),PIXEL_COVERAGE(0x71),PIXEL_COVERAGE(0x72),PIXEL_COVERAGE(0x73),
    PIXEL_COVERAGE(0x74),PIXEL_COVERAGE(0x75),PIXEL_COVERAGE(0x76),PIXEL_COVERAGE(0x77),
    PIXEL_COVERAGE(0x78),PIXEL_COVERAGE(0x79),PIXEL_COVERAGE(0x7a),PIXEL_COVERAGE(0x7b),
    PIXEL_COVERAGE(0x7c),PIXEL_COVERAGE(0x7d),PIXEL_COVERAGE(0x7e),PIXEL_COVERAGE(0x7f),
    PIXEL_COVERAGE(0x80),PIXEL_COVERAGE(0x81),PIXEL_COVERAGE(0x82),PIXEL_COVERAGE(0x83),
    PIXEL_COVERAGE(0x84),PIXEL_COVERAGE(0x85),PIXEL_COVERAGE(0x86),PIXEL_COVERAGE(0x87),
    PIXEL_COVERAGE(0x88),PIXEL_COVERAGE(0x89),PIXEL_COVERAGE(0x8a),PIXEL_COVERAGE(0x8b),
    PIXEL_COVERAGE(0x8c),PIXEL_COVERAGE(0x8d),PIXEL_COVERAGE(0x8e),PIXEL_COVERAGE(0x8f),
    PIXEL_COVERAGE(0x90),PIXEL_COVERAGE(0x91),PIXEL_COVERAGE(0x92),PIXEL_COVERAGE(0x93),
    PIXEL_COVERAGE(0x94),PIXEL_COVERAGE(0x95),PIXEL_COVERAGE(0x96),PIXEL_COVERAGE(0x97),
    PIXEL_COVERAGE(0x98),PIXEL_COVERAGE(0x99),PIXEL_COVERAGE(0x9a),PIXEL_COVERAGE(0x9b),
    PIXEL_COVERAGE(0x9c),PIXEL_COVERAGE(0x9d),PIXEL_COVERAGE(0x9e),PIXEL_COVERAGE(0x9f),
    PIXEL_COVERAGE(0xa0),PIXEL_COVERAGE(0xa1),PIXEL_COVERAGE(0xa2),PIXEL_COVERAGE(0xa3),
    PIXEL_COVERAGE(0xa4),PIXEL_COVERAGE(0xa5),PIXEL_COVERAGE(0xa6),PIXEL_COVERAGE(0xa7),
    PIXEL_COVERAGE(0xa8),PIXEL_COVERAGE(0xa9),PIXEL_COVERAGE(0xaa),PIXEL_COVERAGE(0xab),
    PIXEL_COVERAGE(0xac),PIXEL_COVERAGE(0xad),PIXEL_COVERAGE(0xae),PIXEL_COVERAGE(0xaf),
    PIXEL_COVERAGE(0xb0),PIXEL_COVERAGE(0xb1),PIXEL_COVERAGE(0xb2),PIXEL_COVERAGE(0xb3),
    PIXEL_COVERAGE(0xb4),PIXEL_COVERAGE(0xb5),PIXEL_COVERAGE(0xb6),PIXEL_COVERAGE(0xb7),
    PIXEL_COVERAGE(0xb8),PIXEL_COVERAGE(0xb9),PIXEL_COVERAGE(0xba),PIXEL_COVERAGE(0xbb),
    PIXEL_COVERAGE(0xbc),PIXEL_COVERAGE(0xbd),PIXEL_COVERAGE(0xbe),PIXEL_COVERAGE(0xbf),
    PIXEL_COVERAGE(0xc0),PIXEL_COVERAGE(0xc1),PIXEL_COVERAGE(0xc2),PIXEL_COVERAGE(0xc3),
    PIXEL_COVERAGE(0xc4),PIXEL_COVERAGE(0xc5),PIXEL_COVERAGE(0xc6),PIXEL_COVERAGE(0xc7),
    PIXEL_COVERAGE(0xc8),PIXEL_COVERAGE(0xc9),PIXEL_COVERAGE(0xca),PIXEL_COVERAGE(0xcb),
    PIXEL_COVERAGE(0xcc),PIXEL_COVERAGE(0xcd),PIXEL_COVERAGE(0xce),PIXEL_COVERAGE(0xcf),
    PIXEL_COVERAGE(0xd0),PIXEL_COVERAGE(0xd1),PIXEL_COVERAGE(0xd2),PIXEL_COVERAGE(0xd3),
    PIXEL_COVERAGE(0xd4),PIXEL_COVERAGE(0xd5),PIXEL_COVERAGE(0xd6),PIXEL_COVERAGE(0xd7),
    PIXEL_COVERAGE(0xd8),PIXEL_COVERAGE(0xd9),PIXEL_COVERAGE(0xda),PIXEL_COVERAGE(0xdb),
    PIXEL_COVERAGE(0xdc),PIXEL_COVERAGE(0xdd),PIXEL_COVERAGE(0xde),PIXEL_COVERAGE(0xdf),
    PIXEL_COVERAGE(0xe0),PIXEL_COVERAGE(0xe1),PIXEL_COVERAGE(0xe2),PIXEL_COVERAGE(0xe3),
    PIXEL_COVERAGE(0xe4),PIXEL_COVERAGE(0xe5),PIXEL_COVERAGE(0xe6),PIXEL_COVERAGE(0xe7),
    PIXEL_COVERAGE(0xe8),PIXEL_COVERAGE(0xe9),PIXEL_COVERAGE(0xea),PIXEL_COVERAGE(0xeb),
    PIXEL_COVERAGE(0xec),PIXEL_COVERAGE(0xed),PIXEL_COVERAGE(0xee),PIXEL_COVERAGE(0xef),
    PIXEL_COVERAGE(0xf0),PIXEL_COVERAGE(0xf1),PIXEL_COVERAGE(0xf2),PIXEL_COVERAGE(0xf3),
    PIXEL_COVERAGE(0xf4),PIXEL_COVERAGE(0xf5),PIXEL_COVERAGE(0xf6),PIXEL_COVERAGE(0xf7),
    PIXEL_COVERAGE(0xf8),PIXEL_COVERAGE(0xf9),PIXEL_COVERAGE(0xfa),PIXEL_COVERAGE(0xfb),
    PIXEL_COVERAGE(0xfc),PIXEL_COVERAGE(0xfd),PIXEL_COVERAGE(0xfe),PIXEL_COVERAGE(0xff)
};

#endif


